#pragma once
#include "linear_algebra/matrix3d.h"
#include "linear_algebra/matrix4d.h"
#include "linear_algebra/matrix4hom.h"
#include "linear_algebra/point3d.h"
#include "linear_algebra/transform.h"
#include "linear_algebra/vector3d.h"
#include "linear_algebra/vector4d.h"
#include "linear_algebra/fastcalc.h"